#!/bin/bash

# Function to display usage information
usage() {
  echo "Usage: $0 experiment [get|launch|prefix] <experiment_name>"
  echo "       $0 nodes [start|stop] <node_name>"
  exit 1
}

start_node(){
  local node="$1"

  TOKEN="$(slices auth id-token pos)"
  curl -s -X PATCH "https://post5g-backend.slices-be.eu/r2lab/$node"   -H 'accept: application/json' -H "Bearer: ${TOKEN}"

  curl -X 'PATCH' \
  "https://post5g-backend.slices-be.eu/r2lab/$node/" \
  -H 'accept: application/json' \
  -H "Bearer: ${TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{
  "state": "ON"
  }'
}

stop_node(){
  local node="$1"

  TOKEN="$(slices auth id-token pos)"
  curl -s -X PATCH "https://post5g-backend.slices-be.eu/r2lab/$node"   -H 'accept: application/json' -H "Bearer: ${TOKEN}"

  curl -X 'PATCH' \
  "https://post5g-backend.slices-be.eu/r2lab/$node/" \
  -H 'accept: application/json' \
  -H "Bearer: ${TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{
  "state": "OFF"
  }'
}

get_experiment_id(){
  local experiment_name="$1"
  local experiment_id=$(slices experiment show $experiment_name --format json |jq .id | tr -d \")

  echo $experiment_id
}

# Function to get floating IPs for a project
get_prefix() {
  local project_id="$1"
  local experiment_name="$2"

  TOKEN="$(slices auth id-token pos)"
  curl -s -X GET "https://post5g-backend.slices-be.eu/prefix/"   -H 'accept: application/json' -H "Bearer: ${TOKEN}"
}

# Function to fetch experiment details
get_experiment() {
  local project_id="$1"
  local experiment_name="$2"
  echo "Fetching details for experiment $project_id / $experiment_name"

  experiment_id=$(get_experiment_id $experiment_name)

  echo $experiment_id

  DIR=xp/$project_id/$experiment_name/

  mkdir -p $DIR
  cd $DIR

  wget -q https://gitlab.inria.fr/slices-ri/blueprints/post-5g/reference_implementation/-/archive/develop/reference_implementation-develop.tar.gz
  tar -xzf reference_implementation-develop.tar.gz
  rm reference_implementation-develop.tar.gz


  TOKEN="$(slices auth id-token pos)"
  curl -s -X GET "https://post5g-backend.slices-be.eu/pos/script/${experiment_id}"   -H 'accept: application/json' -H "Bearer: ${TOKEN}" --output ${experiment_id}.zip
  unzip -qq -o -d reference_implementation-develop/ ${experiment_id}.zip
  chmod a+r -R reference_implementation-develop/

  echo "Details for experiment $experiment_name saved in $DIR"
}

# Function to launch the experiment
launch_experiment() {
  local project_id="$1"
  local experiment_name="$2"
  
  echo "Launching experiment $project_id / $experiment_name"

  DIR=xp/$project_id/$experiment_name/

  cd $DIR/reference_implementation-develop
  chmod u+x pos/deploy.sh
  pos/deploy.sh
}




#########
# Check that the correct number of arguments are passed
if [ "$#" -lt 3 ]; then
  echo "Error: Insufficient arguments."
  usage
fi

# Assign the first and second arguments
type="$1"
command="$2"

# Handle "experiment" related commands
if [ "$type" == "experiment" ]; then
  if [ "$#" -lt 3 ]; then
    echo "Error: Insufficient arguments for experiment."
    usage
  fi

  experiment_name="$3"
  project_id=$(slices project show -f json | jq .name | tr -d \")

  case "$command" in
    get)
      get_experiment "$project_id" "$experiment_name"
      ;;
    launch)
      launch_experiment "$project_id" "$experiment_name"
      ;;
    prefix)
      get_prefix "$project_id" "$experiment_name"
      ;;
    *)
      echo "Error: Invalid command '$command'."
      usage
      ;;
  esac

# Handle "nodes" related commands
elif [ "$type" == "nodes" ]; then
  if [ "$#" -lt 3 ]; then
    echo "Error: Insufficient arguments for nodes."
    usage
  fi

  node_name="$3"

  case "$command" in
    start)
      start_node "$node_name"
      ;;
    stop)
      stop_node "$node_name"
      ;;
    *)
      echo "Error: Invalid command '$command'."
      usage
      ;;
  esac

else
  echo "Error: Invalid type '$type'."
  usage
fi



# # Check that the correct number of arguments are passed
# if [ "$#" -lt 3 ]; then
#   echo "Error: Insufficient arguments."
#   usage
# fi

# # Check that the first argument is "experiment"
# if [ "$1" != "experiment" ]; then
#   echo "Error: The first argument must be 'experiment'."
#   usage
# fi

# # Assign the second argument to a command and the third to experiment_name
# command="$2"
# experiment_name="$3"
# project_id=$(slices project  show -f json | jq .name | tr -d \")

# # Handle the "get" or "launch" commands with functions
# case "$command" in
#   get)
#     get_experiment "$project_id" "$experiment_name"
#     ;;
#   launch)
#     launch_experiment "$project_id"  "$experiment_name"
#     ;;
#   prefix)
#     get_prefix "$project_id"  "$experiment_name"
#     ;;
#   *)
#     echo "Error: Invalid command '$command'."
#     usage
#     ;;
# esac